routes/admin.php
<?php

// AdminController
Route::get('/', 'Admin\AdminController@index')->name('admin');

// Themes
include('admin/themes.php');

// Modules
include('admin/modules.php');

// Posts
include('admin/content.php');

// Custom Posts & Custom Fields
include('admin/custom_posts.php');

// Mensajes
Route::post('mensajes/visto', 'Admin\MensajesController@visto')->name('admin.mensajes.visto');
Route::resource('mensajes', "Admin\MensajesController", ['as' => 'admin']);

// Configuracion
Route::get('configuracion', "Admin\ConfiguracionController@index")->name('admin.configuracion.index');
Route::post('configuracion', "Admin\ConfiguracionController@store")->name('admin.configuracion.store');
Route::get('configuracions', "Admin\ConfiguracionController@index")->name('admin.configuracions.index');
Route::post('configuracions', "Admin\ConfiguracionController@store")->name('admin.configuracions.store');

// Media
Route::post('upload', 'Admin\MediaController@upload')->name('admin.media.upload');
Route::post('crop', 'Admin\MediaController@crop')->name('admin.media.crop');
Route::post('media/get_all', "Admin\MediaController@get_all")->name('admin.media.get_all');
Route::post('media/mass_destroy', "Admin\MediaController@massDestroy")->name('admin.media.mass_destroy');
Route::resource('media', "Admin\MediaController", ['as' => 'admin']);


// Cache
Route::get('cache-clear', "Admin\AdminController@clearCache")->name('admin.cache.clear');

// UserMeta
Route::resource('user_meta', "Admin\UserMetaController", ['as' => 'admin']);

// Notifications
Route::put("notifications/{id}/duplicate", "Admin\NotificationsController@duplicate")->name("admin.notifications.duplicate");
Route::post('notifications/active', 'Admin\NotificationsController@active')->name('admin.notifications.active');
Route::resource('notifications', "Admin\NotificationsController", ['as' => 'admin']);

include('admin/administracion.php');

Route::get('search', 'Admin\SearchController@index')->name('admin.search.index');

// Emails
Route::put("emails/{id}/duplicate", "Admin\EmailsController@duplicate")->name("admin.emails.duplicate");
Route::resource('emails', "Admin\EmailsController", ['as' => 'admin']);
// Chats
Route::resource('chats', "Admin\ChatsController", ['as' => 'admin']);
Route::post('chats/{id}/change-permission', 'Admin\ChatsController@changePermission')->name('chats.change-permission');

Route::resource('coupons', "Admin\CouponsController", ['as' => 'admin']);

routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::pattern('index', 'index|inici|inicio');

Route::get('/robots.txt', function () {
    if (strpos(request()->root(), '6tems.es') !== false ||
        strpos(request()->root(), '6tems.com') !== false) {
        $robotsFile = public_path('endo_robots_disallow.txt');
    } else {
        $robotsFile = public_path('endo_robots.txt');

        $frontRobotsFile = public_path(config('front_theme') . 'robots.txt');
        if (file_exists($frontRobotsFile)) {
            $robotsFile = $frontRobotsFile;
        }
    }

    return response()->file($robotsFile);
});

Route::get('/sitemap.xml', function () {
    $frontSitemapFile = public_path(config('front_theme') . 'sitemap.xml');
    if (file_exists($frontSitemapFile)) {
        return response()->file($frontSitemapFile);
    }
    return response( '',404);
});

Route::prefix('{locale}')->group(function () {
    if (\Illuminate\Support\Facades\Schema::hasTable('configuracions')) {
        $home_page = \App\Models\Configuracion::get_config('home_page');
        if (!empty($home_page)) {
            Route::get('/', function () use ($home_page) {
                return app(\App\Http\Controllers\PostsController::class)->callAction('show', ['item' => $home_page]);
            });
        }
    }

    // Auth
    Auth::routes();

    // Home
    Route::get('/{index?}', 'HomeController@index')->name('index');

    // ADMIN
    Route::group(['middleware' => ['rols', 'auth'], 'prefix' => 'admin'], function () {
        include('admin.php');
    });

    Route::any('ajax', 'AjaxController@index')->name('ajax'); 
});

Route::fallback('PostsController@process_routes');

app/Http/Controllers/Admin/MensajesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Chat;
use Illuminate\Http\Request;
use App\Notifications\EmailNotification;
use App\User;
use App\Models\Mensaje;
use Auth;
use DB;

class MensajesController extends AdminController
{
    protected $section_title;
    protected $section_icon;
    protected $section_route;

    public function __construct() {
        parent::__construct();
        $this->section_title = __('Messages');
        $this->section_icon = 'message';
        $this->section_route = 'admin.mensajes';
    }

    public function index() {

        $type = !empty(request()->type) ? request()->type : 'chat';

        $user_avatar_default = asset('storage/avatars/user-endo.jpg');
        $my_user_avatar = $user_avatar_default;
        $avatar_pub = public_path('storage/avatars/' . Auth::user()->avatar);
        if ( file_exists($avatar_pub) ) $my_user_avatar = asset('storage/avatars/' . Auth::user()->avatar);

        if ( Auth::user()->rol->level >= Mensaje::ROL_LEVEL_LIMIT ) {
            $chats = Mensaje::where('type', $type)
            ->selectRaw('mensajes.chat, MAX(mensajes.created_at)')
            ->groupBy(['mensajes.chat'])
            ->orderByRaw('MAX(mensajes.created_at) desc')
            ->pluck('mensajes.chat');
        } else {
            $chats = Mensaje::where('type', $type)->where(function ($query) {
                $query->where('user_id', Auth::user()->id)->orWhere('to', Auth::user()->id);
            })
            ->selectRaw('mensajes.chat, MAX(mensajes.created_at)')
            ->groupBy(['mensajes.chat'])
            ->orderByRaw('MAX(mensajes.created_at) desc')
            ->pluck('mensajes.chat');
        }
        
        $items = array();
        foreach ( $chats as $chat ) {
            if ( Auth::user()->rol->level >= Mensaje::ROL_LEVEL_LIMIT ) {
                $mensajes = Mensaje::where('chat', $chat)->where('type', $type)->orderBy('created_at')->withAll()->get();
            } else {
                $mensajes = Mensaje::where('chat', $chat)->where('type', $type)
                ->where(function ($query) {
                    $query->where('user_id', Auth::user()->id)->orWhere('to', Auth::user()->id);
                })
                ->orderBy('created_at')->withAll()->get();
            }
            $last_mensaje = $mensajes->last();
            $last_mensaje_chat = !empty($last_mensaje) ? $last_mensaje->get_chat : null;

            // All Params
            $all_params = array();
            if ( Auth::user()->rol->level >= Mensaje::ROL_LEVEL_LIMIT ) {
                $params = Mensaje::where('chat', $chat)->where('type', $type)
                ->whereNotNull('params')->orderBy('created_at', 'DESC')->pluck('params');
            } else {
                $params = Mensaje::where('chat', $chat)->where('type', $type)
                ->where(function ($query) {
                    $query->where('user_id', Auth::user()->id)->orWhere('to', Auth::user()->id);
                })
                ->whereNotNull('params')->orderBy('created_at', 'DESC')->pluck('params');
            }
            foreach ( $params as $param ) $all_params = array_merge(json_decode($param, TRUE), $all_params);

            $chat_users = $last_mensaje->get_users();
            $user_id = 0;
            $user_name = [];
            $user_email = [];
            $user_avatar = $user_avatar_default;
            
            foreach ( $chat_users as $chat_user ) {
                if ( is_int($chat_user) ) {
                    $user = User::find($chat_user);

                    if ( empty($user) ) continue;

                    $user_email[] = $user->email;
                    $user_name[] = $user->name;
                    if ( count($chat_users) == 1 )  {
                        $user_name = [$user->fullname()];
                        if ( !empty($user->avatar) ) {
                            $avatar = asset('storage/avatars/' . $user->avatar);
                            $avatar_pub = public_path('storage/avatars/' . $user->avatar);
                            if ( file_exists($avatar_pub) ) $user_avatar = $avatar;
                        }
                    }
                } else {
                    $parts = explode('##', $chat_user);
                    $user_id = $parts[1];
                    $user_name[] = $parts[0];
                    $user_email[] = $parts[1];
                    $user_avatar = $user_avatar_default;
                }
            }

            /* Botones chats */
            $buttons = array();
            if ( 
                !empty($last_mensaje) && !empty($last_mensaje_chat) && 
                !empty($last_mensaje_chat->get_buttons()) 
            ) {
                
                $chat_btns = $last_mensaje_chat->get_buttons();
                foreach ( $chat_btns as $k_btn => $chat_btn ) {
                    if ( empty($chat_btn) ) continue;

                    $chat_btn_parts = explode('##', $chat_btn);

                    if (empty($all_params[ $chat_btn_parts[0] ])) {
                        continue;
                    }
                    
                    $btn_action_url = $all_params[ $chat_btn_parts[0] ];
                    
                    $btn_action_txt = '';
                    if ( !empty($chat_btn_parts[1]) ) {
                        $btn_action_txt = $chat_btn_parts[1];
                    }

                    if ( empty($btn_action_txt) ) $btn_action_txt = _('Button') . " $k_btn";

                    $btn_action_txt_btn = '';
                    if ( !empty($chat_btn_parts[2]) ) {
                        $btn_action_txt_btn = $chat_btn_parts[2];
                    }

                    if ( empty($btn_action_txt_btn) ) $btn_action_txt_btn = $btn_action_txt;

                    $btn_action_js_action = '';
                    if ( !empty($chat_btn_parts[3]) && isset($all_params[$chat_btn_parts[3]]) ) {
                        $btn_action_js_action = $all_params[$chat_btn_parts[3]];
                    }

                    if ( !empty($btn_action_url) ) {
                        $buttons[] = [
                            'text' => $btn_action_txt,
                            'url' => $btn_action_url,
                            'text-btn' => $btn_action_txt_btn,
                            'action' => $btn_action_js_action
                        ];
                    }
                    
                }
            }
            /* end Botones chats */

            $item = new \stdClass();
            $item->chat = str_replace('.', '-', str_replace('@', '-', $chat));
            $item->chat_noencode = $chat;
            $item->mensajes = $mensajes;
            $item->user_name = !empty($user_name) ? implode(', ', $user_name) : Auth::user()->fullname();
            $item->user_email = count($chat_users) == 1 ? reset($user_email) : '';
            $item->user_id = $user_id;
            $item->user_avatar = !empty($user_name) ? $user_avatar : $my_user_avatar;
            $item->last_mensaje = $last_mensaje;
            $item->buttons = $buttons;
            $items[] = $item;
        }
        
        return view('Admin::default.messaging', array(
            'items' => $items,
            'section_title' => $this->section_title,
            'section_icon' => $this->section_icon,
            'route' => $this->section_route,
            'user_avatar_default' => $user_avatar_default,
        ));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $mensaje = new Mensaje();
        $mensaje->chat = $data['chat_id'];
        $mensaje->user_id = Auth::user()->id;
        $mensaje->mensaje = $data['mensaje'];
        $mensaje->type = $data['type'];
        $mensaje->fitxer = '';
        $mensaje->name = '';
        $mensaje->email = '';

        /* TO */
        if ( !empty($data['to']) ) $mensaje->to = $data['to'];
        else {
            $last_mensaje = Mensaje::where('chat', $mensaje->chat)->where('type', $mensaje->type)
            ->orderBy('created_at', 'ASC')->get()->last();
            $mensaje->to = 0;
            if ( !empty($last_mensaje->user_id) && $last_mensaje->user_id != Auth::user()->id )
                $mensaje->to = $last_mensaje->user_id;
            else if ( !empty($last_mensaje->to) && $last_mensaje->to != Auth::user()->id )
                $mensaje->to = $last_mensaje->to;
        }
        /* end TO */

        /* Guardar ultims params */
        $all_params = array();
        if ( Auth::user()->rol->level >= Mensaje::ROL_LEVEL_LIMIT ) {
            $params = Mensaje::where('chat', $mensaje->chat)->where('type', $mensaje->type)
            ->whereNotNull('params')->orderBy('created_at', 'DESC')->pluck('params');
        } else {
            $params = Mensaje::where('chat', $mensaje->chat)->where('type', $mensaje->type)
            ->where(function ($query) {
                $query->where('user_id', Auth::user()->id)->orWhere('to', Auth::user()->id);
            })
            ->whereNotNull('params')->orderBy('created_at', 'DESC')->pluck('params');
        }

        foreach ( $params as $param ) $all_params = array_merge(json_decode($param, TRUE), $all_params);
        if ( !empty($all_params) ) {
            $mensaje->params = json_encode($all_params);
        }
        /* end Guardar ultims params */

        
        if ( $mensaje->save() ) {

            if ( isProEnv() ) {
                $chat_users = $mensaje->get_users();

                foreach ( $chat_users as $chat_user ) {
                    if ( is_int($chat_user) ) $usuario = User::find( $chat_user );
                    else {

resources/views/admin/mensaje/index.blade.php
@extends('layouts.admin')

@section('section-title')
    @Lang('Contact') @Lang('Messages')
@endsection

@section('content')
<div class="panel-body">
<div class="container">
<div class="card-noconflict">
    <div class="inbox_msg" style="border: none;">

        <!-- CONTACTES -->
        <div class="inbox_people">
            <div class="headind_srch">
                <div class="recent_heading">
                    <h4>@Lang('Users')</h4>
                </div>
                {{--
                <div class="srch_bar">
                    <div class="stylish-input-group">
                        <input type="text" class="search-bar"  placeholder="Search" >
                        <span class="input-group-addon">
                            <button type="button"> <i class="fa fa-search" aria-hidden="true"></i> </button>
                        </span>
                    </div>
                </div>
                --}}
            </div>
          

            <div class="inbox_chat">

            @php($active_chat = null)
            @foreach ( $users as $key => $user )
                @if($key == 0) @php($active_chat = $user->id) @endif
                @php($last_mensaje = $user->contactar_mensajes()->latest()->first())
                <div class="chat_list user_id-{{$user->id}} @if($key == 0) active_chat @endif" onclick="seleccionar_chat( {{$user->id}} );">
                    <div class="chat_people">
                        <div class="chat_img"> <img class="avatar-icon" src="{{ asset('storage/avatars/' . $user->avatar) }}"> </div>
                        <div class="chat_ib {{ !$last_mensaje->visto ? 'nuevo_mensaje' : '' }}">
                            <h5>{{$user->fullname()}} <span class="chat_date">{{$last_mensaje->created_at->format('G:i · d/m/Y')}}</span></h5>
                            <p>{{ $last_mensaje->mensaje }}</p>
                        </div>
                    </div>
                </div>
            @endforeach
                
            </div>
        </div>
        <!-- end CONTACTES -->

        <!-- MISSATGES -->
        <div class="mesgs">
        
        @foreach ( $users as $key => $user )
            @php( $mensajes = \App\User::find($user->id)->contactar_mensajes()->get()->sortBy('created_at') )
            <div class="msg_history" id="user_id-{{$user->id}}" style="display:none;">
            
                @foreach ( $mensajes as $mensaje )
                    @if ( $mensaje->from == $user->id )
                        <div class="incoming_msg">
                            <div class="incoming_msg_img"> <img class="avatar-icon" src="{{ asset('storage/avatars/' . $mensaje->from()->first()->avatar) }}"> </div>
                            <div class="received_msg">
                                <div class="received_withd_msg">
                                    <p>{{$mensaje->mensaje}}</p>
                                    @if ($mensaje->fitxer != '')
                                    <span class="fitxer"><a target="_blank" title="{{$mensaje->fitxer}}" href="{{ asset('storage/'.$mensaje->fitxer) }}"><i class="material-icons">description</i></a></span>
                                    @endif
                                    <span class="time_date">{{$mensaje->created_at->format('G:i · d/m/Y')}}</span>
                                </div>
                            </div>
                        </div>
                    @else
                        <div class="outgoing_msg">
                            <div class="sent_msg">
                            <p>{{$mensaje->mensaje}}</p>
                                <span class="time_date">{{$mensaje->created_at->format('G:i · d/m/Y')}}</span>
                            </div>
                        </div>
                    @endif

                
                @endforeach

            </div>

        @endforeach
            
            <!-- TYPE A MESSAGE -->
            <div class="type_msg">
                <div class="input_msg_write">
                    {{--<input id="mensaje-box" type="text" class="write_msg" placeholder="@Lang('Type a message')" />--}}
                    <textarea id="mensaje-box" type="text" class="write_msg" placeholder="@Lang('Type a message')"></textarea>
                    <button id="enviar_missatge_btn" title="@Lang('Send')" class="msg_send_btn btn btn-info bmd-btn-fab bmd-btn-fab-sm" type="button"><i style="line-height: 1.25;" class="material-icons" aria-hidden="true">send</i></button>
                </div>
            </div>
            
        </div>
        <!-- end MISSATGES -->

    </div>
</div>
</div>
</div>
@endsection	

@section('styles')
<link href="{{asset('css/endo-admin-messaging.css')}}" rel="stylesheet" type="text/css">
@endsection

@section('scripts')
<script>
    var $active_chat = {{$active_chat}};
    var $last_update_chat = new Date();

    $(document).ready(function(){
        seleccionar_chat( '{{ $active_chat }}' );
    });

    function seleccionar_chat( user_id ) {
        $('.msg_history').hide();
        $('.chat_list').removeClass('active_chat');
        $('.chat_list.user_id-' + user_id).addClass('active_chat');
        $('#user_id-' + user_id).show();
        $('#user_id-' + user_id).animate({ scrollTop: $('#user_id-' + user_id).prop("scrollHeight")}, 0);
        $active_chat = user_id;

        // Mensaje visto
        $.ajax({
            url: '{{ route('admin.mensajes.visto') }}',
            method: 'POST',
            data: {'_token': '{{csrf_token()}}', 'user_id': user_id},
            success: function(data) {
                $('.chat_list.user_id-' + user_id + ' .chat_ib.nuevo_mensaje').removeClass('nuevo_mensaje');
            }
        });
    }

    function date_to_str(d) {
        var d_aux = d.getDate();
        var m_aux = d.getMonth() + 1;
        //return d.getFullYear() + '-' + (m_aux > 9 ? m_aux : '0' + m_aux) + '-' + (d_aux > 9 ? d_aux : '0' + d_aux);
        return (d_aux > 9 ? d_aux : '0' + d_aux) + '/' + (m_aux > 9 ? m_aux : '0' + m_aux) + '/' + d.getFullYear();
    }

    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    $('#enviar_missatge_btn').click(function(){
        var user_id = $active_chat;
        var mensaje = $('#mensaje-box').val();
        
        $.ajax({
            url: '{{ route('admin.mensajes.store') }}',
            method: 'POST',
            data: {'_token': '{{csrf_token()}}', 'mensaje': mensaje, 'user_id': user_id},
            success: function(data) {
                if ( data == 'KO' ) alert('Error al enviar el missatge.')
                var ahora = new Date();
                var hora = ahora.toLocaleString('es-ES', { hour: '2-digit', minute: '2-digit', hour12: false });
                var fecha = date_to_str(ahora);
                $('#user_id-' + user_id).append(`
                    <div class="outgoing_msg">
                        <div class="sent_msg">
                        <p>` + mensaje + `</p>
                            <span class="time_date">` + hora + ` · ` + fecha + `</span>
                        </div>
                    </div>
                `);
                $('#user_id-' + user_id).animate({ scrollTop: $('#user_id-' + user_id).prop("scrollHeight")}, 0);
                $('#mensaje-box').val('');
            }
        });
    });
</script>
@endsection